### ISSUE TITLE
Won't start on macOS BigSur

### ISSUE THREAD

**Issue by frenck** [timmo001/system-bridge#116]
# Description

The application doesn't start.

## How to reproduce the issue (if applicable)

- Download DMG release
- Open it, drag system-bridge into application folder.
- Start application.

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/195327/112297035-afa87280-8c95-11eb-8edb-88bdbef61398.png)

## Additional information

macOS: BigSur 11.2.2
Version: v1.0.5

**Comment by timmo001** [comment]
I've just released a new version. Can you give it a download and see if it fixes the issue?

**Comment by frenck** [comment]
Yup 👍 Works!
