### ISSUE TITLE
Empty release file:  linux-out.tar.gz

### ISSUE THREAD

**Issue by pschmitt** [timmo001/system-bridge#1171]
### Description

Was a bit thrown off by the archive size: 242 Bytes and indeed, it's an empty archive.
Something is wrong in the artifact generation for Linux: 

Refs:
- https://github.com/timmo001/system-bridge/actions/runs/1591835683
- https://github.com/timmo001/system-bridge/releases/tag/v2.8.0

### What Platform / OS are you running?

Linux

### What version are you running?

2.8.0, 2.8.1

**Comment by timmo001** [comment]
Fixed in updated https://github.com/timmo001/workflows
