### ISSUE TITLE
Command endpoint does not respond with success and message

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#1179]
### Description

![image](https://user-images.githubusercontent.com/28114703/146755336-21969879-ac4e-4a6f-89e8-a4bc9f467344.png)

Raised from https://github.com/home-assistant/core/issues/62361

### What Platform / OS are you running?

Windows

### What version are you running?

2.8.0

**Comment by VNRARA** [comment]
@timmo001 need anything from my side still?
