### ISSUE TITLE
macOS icon is a bit... weird?

### ISSUE THREAD

**Issue by frenck** [timmo001/system-bridge#124]
# Description

The system bridge icon looks odd on macOS 😬 

## How to reproduce the issue (if applicable)

Install & run :)

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/195327/112720533-3f9d2500-8eff-11eb-8329-bd43b808aaa6.png)

## Additional information

It does work

**Comment by timmo001** [comment]
I've limited the dock icon to 32x32, hopefully this fixes the macos specific issue! 😃
