### ISSUE TITLE
Useless icon in task tray on macOS

### ISSUE THREAD

**Issue by frenck** [timmo001/system-bridge#125]
# Description

Shows up in macOS taksbar, but not window there.
It took me a moment to realize it is also in the systemtray.

## How to reproduce the issue (if applicable)

Install & run 

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/195327/112720559-69564c00-8eff-11eb-98ef-6281873b27fd.png)

## Additional information

I think it makes sense to remove it from here.

**Comment by timmo001** [comment]
I've pushed a new version that should use the macos supported `icns`

**Comment by frenck** [comment]
Well, it shows up with an icon now... but uh... why is it there in the first place?

**Comment by timmo001** [comment]
Not sure... Seems to be some setting or command I need to call to hide it from the tray/taskbar/dock in the electron app.

I thought `app.dock.hide()` would have done it:

https://github.com/timmo001/system-bridge/blob/8ea37731591dc7b9c14859b58eb06c31ea777730/src/index.ts#L209
