### ISSUE TITLE
High CPU & RAM usage

### ISSUE THREAD

**Issue by jorbig** [timmo001/system-bridge#1292]
### Description

I installed the latest release (2.8.3) on Windows, and it works correctly, except that it makes my computer unstable due to a very high RAM (and apparently also CPU) usage:

![system bridge problem](https://user-images.githubusercontent.com/49766553/151666912-3f4aa033-7c40-49d3-bf1c-51ea6a8b8daf.png)

Is this to be expected?

### What Platform / OS are you running?

Windows

### What version are you running?

2.8.3

**Comment by jorbig** [comment]
In resource control I see it opens a powershell.exe every second or so. Why is that?
![image](https://user-images.githubusercontent.com/49766553/151678441-2029f9ab-63a2-4ac9-a6e4-d40a0b64de22.png)

**Comment by sjdvda** [comment]
Same issue here. Since updating to 2.8.3, I'm seeing very high CPU and RAM usage.

**Comment by timmo001** [comment]
Made some changes to make sure only one task is run on the schedule at a time. The initial data grab will max out the CPU, but after this, there should only be moderate use when the observer schedule runs
