### ISSUE TITLE
Console log errors

### ISSUE THREAD

**Issue by SilentException** [timmo001/system-bridge#1778]
### Description

Decided to upgrade from 2.8.4. Followed install Instructions, got Python 3.10 from Windows Store and installed all required packages / dependencies without issues.

Started backend using command `python -m systembridgebackend`.

Console was filled with messages and many errors as well. I have seen some database and network related ones, then the backend restarted, then there was an error each time CPU sensor was updated.

I then decided to close backend using Ctrl+C, but it didn't close, no matter how long I've waited. Figured to try Exit command in GUI but it just produced more errors. I had to close python process using Task Manager at the end.

Is this expected behavior? Logs attached..-

[system-bridge (first start).log](https://github.com/timmo001/system-bridge/files/8939442/system-bridge.first.start.log)
[system-bridge-console (first start).log](https://github.com/timmo001/system-bridge/files/8939443/system-bridge-console.first.start.log)

### What Platform / OS are you running?

Windows

### What version are you running?

3.2.1

### Anything in the logs or a references that might be useful?

```txt
Couple of errors related to SQL/database
Couple of network errors
Error on sensors update
Errors when closing backend (not GUI)
```

**Comment by timmo001** [comment]
Please upgrade and see if your issues are fixed

**Comment by timmo001** [comment]
OK, I'll close this one and continue to investigate on #1779
