### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by WalkeLee** [timmo001/system-bridge#1828]
### Description

FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/applications/systembridge.desktop'

### What Platform / OS are you running?

Linux

### What version are you running?

System Bridge 3.3.0

### Anything in the logs or a references that might be useful?

```txt
root@ProxmoxVE:~# python3 -m systembridgebackend --no-gui
2022-07-06 20:28:44 INFO (MainThread) [__main__.Main] System Bridge 3.3.0: Startup
2022-07-06 20:28:44 INFO (MainThread) [__main__.Main] Autostart enabled: False
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/systembridgebackend/__main__.py", line 54, in <module>
    Main()
  File "/usr/local/lib/python3.9/dist-packages/systembridgebackend/__main__.py", line 37, in __init__
    create_shortcuts()
  File "/usr/local/lib/python3.9/dist-packages/systembridgebackend/shortcut/__init__.py", line 16, in create_shortcuts
    create_linux_shortcuts()
  File "/usr/local/lib/python3.9/dist-packages/systembridgebackend/shortcut/linux.py", line 21, in create_linux_shortcuts
    with open(path, "w", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/applications/systembridge.desktop'
```

**Comment by WalkeLee** [comment]
<img width="1255" alt="截屏2022-07-06 21 07 43" src="https://user-images.githubusercontent.com/39288935/177557594-3e7b4ffd-4668-4715-8874-366bad2f7d69.png">

**Comment by WalkeLee** [comment]
I install and run on ProxmoxVE，python3.9，and to my Home Assistant 
I feel it has something to do with nogui, but I can't solve the problem

**Comment by delta010** [comment]
I also have the same error, the CLI is working ok but the GUI is not

**Comment by WalkeLee** [comment]
proxmox-ve: 7.2-1 (running kernel: 5.15.39-1-pve)
pve-manager: 7.2-5 (running version: 7.2-5/12f1e639)
pve-kernel-5.15: 7.2-6
pve-kernel-helper: 7.2-6
pve-kernel-5.15.39-1-pve: 5.15.39-1
pve-kernel-5.15.30-2-pve: 5.15.30-3
ceph-fuse: 16.2.9-pve1
corosync: 3.1.5-pve2
criu: 3.15-1+pve-1
glusterfs-client: 9.2-1
ifupdown2: 3.1.0-1+pmx3
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve1
libproxmox-acme-perl: 1.4.2
libproxmox-backup-qemu0: 1.3.1-1
libpve-access-control: 7.2-3
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.2-2
libpve-guest-common-perl: 4.1-2
libpve-http-server-perl: 4.1-3
libpve-storage-perl: 7.2-5
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 4.0.12-1
lxcfs: 4.0.12-pve1
novnc-pve: 1.3.0-3
proxmox-backup-client: 2.2.3-1
proxmox-backup-file-restore: 2.2.3-1
proxmox-mini-journalreader: 1.3-1
proxmox-widget-toolkit: 3.5.1
pve-cluster: 7.2-1
pve-container: 4.2-1
pve-docs: 7.2-2
pve-edk2-firmware: 3.20210831-2
pve-firewall: 4.2-5
pve-firmware: 3.4-2
pve-ha-manager: 3.3-4
pve-i18n: 2.7-2
pve-qemu-kvm: 6.2.0-11
pve-xtermjs: 4.16.0-1
qemu-server: 7.2-3
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.7.1~bpo11+1
vncterm: 1.7-1
zfsutils-linux: 2.1.4-pve1
