### ISSUE TITLE
Settings not available

### ISSUE THREAD

**Issue by madman2143** [timmo001/system-bridge#1856]
### Description

I installed System Bridge using the supplied Documentation but sadly the settings are not available, there is a error reported in the GUI.

The error reported is the following:

Application error: a client-side exception has occurred (see the browser console for more information).

Where do I access the browser console in this situation? I sadly am not that fluent in Python.

### What Platform / OS are you running?

Windows

### What version are you running?

3.3.4

**Comment by timmo001** [comment]
The easiest way to access the console is to access the GUI logs and copy the URL into your normal browser. You can the access the console the usual way (F12 for chrome based browsers)

**Comment by timmo001** [comment]
Merging with #1779
