### ISSUE TITLE
System Bridge to HA - no entities shown

### ISSUE THREAD

**Issue by Anto79-ops** [timmo001/system-bridge#1928]
### Description

Hi All,

Just wanted to move my discussion to an issue now (details in the link):

https://github.com/timmo001/system-bridge/discussions/1829#discussioncomment-3403209

I still can't get System Bridge (SB) to work in HA. No entities are being reported.

Its running on my Ubuntu 22.04 machine, I can access the system bridge via weburl, and I see all the data there.

`http://192.168.1.139:9170/app/data.html?apiKey=[redacted API]&apiPort=9170`

HA auto discovers SB, it accepts my token, but no entities in HA while it runs. After a while, like hours, [another issue happens](https://github.com/timmo001/system-bridge/issues/1876), but I just wanted to solve the issue of getting information into HA first.

Perhaps its not not working with Ubuntu 22.04? 

IF you have any ideas? that would be awesome, thanks!

### What Platform / OS are you running?

Linux

### What version are you running?

3.4.4

### Anything in the logs or a references that might be useful?

```txt
Home Assistant 2022.8.5
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest
```

**Comment by Anto79-ops** [comment]
just updated to system bridge 3.4.5 and it works!!

thank you very much!

**Comment by Anto79-ops** [comment]
Ahhh ok it worked for about 5 minutes and I saw entities being reported to HA, but then they became unavailable.

I deleted the integration and tried again, but now it's back to not working.

The error in the logs are a bit different now.

`Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 7:00:46 PM (1 occurrences)
Last logged: 7:00:46 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 492, in listen
    await self.listen_for_messages(callback=_callback_message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 505, in listen_for_messages
    message = await self.receive_message()
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 527, in receive_message
    raise ConnectionClosedException("Connection closed to server")
systembridgeconnector.exceptions.ConnectionClosedException: Connection closed to server`

And

`Logger: homeassistant.config_entries
Source: config_entries.py:1031
First occurred: 6:39:03 PM (5 occurrences)
Last logged: 7:01:45 PM

Config entry '192.168.1.139' for system_bridge integration not ready yet: Could not connect to 192.168.1.139 (192.168.1.139).; Retrying in background
Config entry '192.168.1.139' for system_bridge integration not ready yet: Timed out waiting for 192.168.1.139 (192.168.1.139).; Retrying in background`

Got excited there for a few minutes.

**Comment by timmo001** [comment]
I'm unsure what is happening here.

I've set up a Ubuntu 22.04 instance and installed the application following the instructions in the [docs](https://system-bridge.timmo.dev/docs/install) and the Home Assistant can connect fine and holds the connection.

I don't see any errors show up that could point to what your issue is. Do you have anything special about your setup, such as a custom firewall or any special networking?

**Comment by Anto79-ops** [comment]
thanks @timmo001 for looking into this for Ubuntu 22.04.

I don't have anything special with the firewall, have just whatever comes standard in Ubuntu 22.04

To install Sysystem bridge, I simple just type below in the command line, one line at a time, except for the the last line,  added 3.10 to the python3.10

```
sudo apt update
sudo apt install lshw upower
sudo apt install python3 python3-pip python3-setuptools python3-wheel
python3.10 -m pip install --upgrade systembridgeshared systembridgebackend systembridgecli systembridgefrontend systembridgegui
```

Installed without any issues.

Could you please detail how you installed it on your Ubuntu 22.04? if its different than the above thanks you!

**Comment by Anto79-ops** [comment]
any logs we can look into to figure this out? 

I've worked with devs before, figuring out issues, and usually involves looking into logs.
