### ISSUE TITLE
could not find a version that satisfies the requirement pywin32==303

### ISSUE THREAD

**Issue by mickel52** [timmo001/system-bridge#1945]
### Description

python -m pip install --upgrade systembridgeshared systembridgebackend systembridgecli systembridgefrontend systembridgegui
i use "python3 ....."
after
2 min install - / -
could not find a version that satisfies the requirement pywin32==303
may be ver python not supported?

### What Platform / OS are you running?

Linux

### What version are you running?

latest

**Comment by julianrinaldi** [comment]
I have the same issue
