### ISSUE TITLE
Empty window for View Data and Open Settings

### ISSUE THREAD

**Issue by mvdwetering** [timmo001/system-bridge#1948]
### Description

When trying the "Open Settings" or "View Data" options from the tray menu an empty window pops up. This reproduces also after restarting System Bridge.

The application seems to be running fine otherwise as I can connect it to the HA integration, just the UI not working.

![image](https://user-images.githubusercontent.com/732514/187071622-b1310720-c91e-4736-8841-fe4f66d0f1ea.png)

### What Platform / OS are you running?

Windows

### What version are you running?

Windows 10.0.19044, System bridge 3.4.4

### Anything in the logs or a references that might be useful?

This is part of the console output. The log paths obtained from the CLI do not exist on my machine.

```txt
qt.webenginecontext:

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.3
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python3
  *  browser-subprocess-path C:\Users\Michel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PySide6\.\QtWebEngineProcess.exe
  *  create-default-gl-context
  *  disable-es3-gl-context
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl desktop

QOpenGLShader::compile(Fragment): ERROR: 4:1: 'textureSampler' : syntax error syntax error


*** Problematic Fragment shader source code ***
#version 110
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#define lowp
#define mediump
#define highp
#line 1
varying highp vec2 uv;uniform sampler2DRect textureSampler;uniform bool swizzle;uniform highp float opacity;void main() {   highp vec4 tmpFragColor = texture2DRect(textureSampler,uv);   tmpFragColor.a *= opacity;   gl_FragColor = swizzle ? tmpFragColor.bgra : tmpFragColor;}
***
```

### Additional information

I am using the Windows Remote Desktop feature to access this machine and it has no display attached, maybe that is causing issues.

**Comment by timmo001** [comment]
The GUI uses Qt for Python, I'm not sure if the remote desktop session could be causing this. I've used a remote session myself, however through VNC to a Windows VM on a Debian machine and had no issues.
