### ISSUE TITLE
CLI does not output api key

### ISSUE THREAD

**Issue by joostlek** [timmo001/system-bridge#2364]
### Description

Hey,

My system bridge doesn't generate an api key.

![image](https://user-images.githubusercontent.com/7083755/230089572-57bc774b-9378-4584-a995-f07c0ddd2084.png)

### What Platform / OS are you running?

Windows

### What version are you running?

3.6.2

**Comment by joostlek** [comment]
Still doesn't work

**Comment by joostlek** [comment]
Still an issue

**Comment by joostlek** [comment]
Guess what, still an issue

**Comment by DeFlanko** [comment]
whenever i try to run it:
``` cmd
C:\systembridge>python -m systembridgecli api-key
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\systembridge\systembridgecli\__main__.py", line 11, in <module>
    from systembridgeshared.common import get_user_data_directory
  File "C:\systembridge\systembridgeshared\common.py", line 10, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'
`

**Comment by joostlek** [comment]
That's probably a different issue, better open a separate issue for this :)

**Comment by timmo001** [comment]
> whenever i try to run it:
> 
> ```batchfile
> C:\systembridge>python -m systembridgecli api-key
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\systembridge\systembridgecli\__main__.py", line 11, in <module>
>     from systembridgeshared.common import get_user_data_directory
>   File "C:\systembridge\systembridgeshared\common.py", line 10, in <module>
>     from appdirs import AppDirs
> ModuleNotFoundError: No module named 'appdirs'
> `
> ```

You will need to generate your directories, Follow the `Linux Headless Server` section to create your `~/.config/user-dirs.dirs`

https://system-bridge.timmo.dev/docs/install-python

**Comment by timmo001** [comment]
Working for me in Python 3.12.0 on Windows 11

Please reopen if still an issue. Only thing I can tell is this could be an issue with particular setups and the `typer` package.

![image](https://github.com/timmo001/system-bridge/assets/28114703/41c84dcc-cd3d-46ec-9b29-7e8a652a10bd)
