### ISSUE TITLE
Deploy does not output full bin directory for systembridgewindowssensors 

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2580]
### Description

https://pypi.org/project/systembridgewindowssensors/#history

### What Platform / OS are you running?

Linux

### What version are you running?

3.8.0.dev30

**Comment by timmo001** [comment]
setup.py doesnt seem to be picking up the root directory

<img width="669" alt="image" src="https://github.com/timmo001/system-bridge/assets/28114703/196211ca-9b7f-4f55-8d04-7a5ead7055cd">
<img width="563" alt="image" src="https://github.com/timmo001/system-bridge/assets/28114703/299f4fb0-b33e-45b6-89d0-8f8efe3f02d5">

**Comment by TheBigNeo** [comment]
Hi
Is this the reason that I can't start the system bridge on my Windows?

```
2023-07-24 10:24:11 ERROR (Thread-3) [systembridgebackend.modules.sensors.Sensors] Windows sensors error: [WinError 2] Das System kann die angegebene Datei nicht finden
```

![image](https://github.com/timmo001/system-bridge/assets/24251966/4e8b337c-c856-4f18-b86f-6d80891c4727)

**Comment by timmo001** [comment]
> [TheBigNeo](/TheBigNeo)

The application should work without windows sensors, you will just be missing some data

**Comment by timmo001** [comment]
This was caused by the upgrade to .NET 7 https://github.com/timmo001/system-bridge/pull/2566
