### ISSUE TITLE
Check if there is a pending restart

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2844]
### Discussed in https://github.com/timmo001/system-bridge/discussions/2790

Windows: https://www.geekbits.io/how-to-view-a-pending-reboot-in-windows/
Linux: /var/run/reboot-required 

- [x] Model: https://github.com/timmo001/system-bridge-models/pull/16
- [x] Backend: https://github.com/timmo001/system-bridge-backend/pull/30
- [x] Home Assistant: https://github.com/home-assistant/core/pull/104095

**Comment by funforums** [comment]
Hey @timmo001, there is indeed a way on Windows to figure out if a restart is pending, but there is a whole lot of registry keys which need to be looked at. A quick search led me here: https://adamtheautomator.com/pending-reboot-registry/
