### ISSUE TITLE
System Bridge fails setup with new processes module

### ISSUE THREAD

**Issue by tkdrob** [timmo001/system-bridge#2877]
### Description

Per the issue in Home Assistant: https://github.com/home-assistant/core/issues/105664

### What Platform / OS are you running?

Linux

### What version are you running?

Windows 10

### Additional information

[system-bridge.log](https://github.com/timmo001/system-bridge/files/13787044/system-bridge.log)

**Comment by timmo001** [comment]
Your logs show you are running version 3.8.2. Please update to the latest version
