### ISSUE TITLE
Backend uses backend version instead of package version when launched from executable

### ISSUE THREAD

**Issue by DeFlanko** [timmo001/system-bridge#2998]
### Description

![image](https://github.com/timmo001/system-bridge/assets/5233969/3e609160-4425-42fa-b706-959005934db3)
![image](https://github.com/timmo001/system-bridge/assets/5233969/cbdf5d23-2096-406e-81f3-2adc84c6b9d9)
![Uploading image.png…]()

### What Platform / OS are you running?

Linux

### What version are you running?

4.1.7

**Comment by timmo001** [comment]
Good spot. This is because https://github.com/timmo001/system-bridge-backend is that version.

TODO:

- [ ] If running in python, use backend version
- [ ] If running as executable, use package version

**Comment by DeFlanko** [comment]
can confrim @timmo001 -- i had to change my Task Schedule action to re-point to `.\System Bridge.exe` with the `--no-gui` option again. 

![image](https://github.com/timmo001/system-bridge/assets/5233969/cbe22ebc-f1be-4341-a31b-475d75e8b9c7)

**Comment by DeFlanko** [comment]
and the versions match as well.
