### ISSUE TITLE
Installed 4.1.7, but reports 4.1.6

### ISSUE THREAD

**Issue by mvdwetering** [timmo001/system-bridge#2999]
### Description

I just downloaded and installed 4.1.7, but it reports as 4.1.6 in Home Assistant and the logs.
This is with the Windows installer System.Bridge_4.1.7_x64-setup.exe

![image](https://github.com/timmo001/system-bridge/assets/732514/44105edb-d67b-4b5b-85d1-0c2778cee50c)

```
2024-04-06 14:50:22 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.1.6: Startup
```

This is probably also why Home Assistant detects there is an update available for 4.1.7.

### What Platform / OS are you running?

Windows

### What version are you running?

System Bridge 4.1.7 (at least that was the expectation)

**Comment by mvdwetering** [comment]
Ow, I now see that this is probably the same as #2998, but not 100% sure.
Please close if duplicate

**Comment by timmo001** [comment]
Yep same as #2998
