### ISSUE TITLE
/api/notification results in 405

### ISSUE THREAD

**Issue by kjake** [timmo001/system-bridge#3017]
### Description

I upgraded from 3.10 to 4.1.8 and previous calls to /api/notification no longer work.  I have validated the apiKey.
Documentation doesn't detail any sort of change to the request that I should be making.

```shell
➜  ~ curl -vvvv --location --request POST 'http://192.168.1.7:9170/api/notification?apiKey=kEy' --header 'Content-Type: application/json' --data-raw '{"title":"Test","message":"Test"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.1.7:9170...
* Connected to 192.168.1.7 (192.168.1.7) port 9170
> POST /api/notification?apiKey=kEy HTTP/1.1
> Host: 192.168.1.7:9170
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
>
< HTTP/1.1 405 Method Not Allowed
< date: Thu, 11 Apr 2024 22:39:19 GMT
< server: uvicorn
< content-length: 31
< content-type: application/json
<
* Connection #0 to host 192.168.1.7 left intact
{"detail":"Method Not Allowed"}%
```

### What Platform / OS are you running?

Windows

### What version are you running?

4.1.8

**Comment by eikw** [comment]
I can confirm this also happens for all other post requests on my linux machine.

**Comment by timmo001** [comment]
These APIs have been removed in 4.x.x

You are also attempting to use apiKey, which is no longer supported.

I have updated the website to reflect the new setup.

Vercel is currently limiting deployments so for now you can access the website docs via `http://localhost:9170/docs` or via the website code:
https://github.com/timmo001/system-bridge-website/tree/master/src/pages/docs

**Comment by kjake** [comment]
Ok... that's unfortunate.  Is there a way to use the websocket instead?

FWIW, "Send system notifications via the API/WebSocket." is still listed as a Feature, if you need to change that.

**Comment by timmo001** [comment]
Yes everything should be done via the websocket nowadays. If you are ok reading python code, the connector will be the most up to date resource for commumicating via the websocket:

https://github.com/timmo001/system-bridge-connector/blob/master/systembridgeconnector/websocket_client.py#L316
