### ISSUE TITLE
Can't change settings from the cli

### ISSUE THREAD

**Issue by bwduncan** [timmo001/system-bridge#3090]
### Description

If you're running headless, it's impossible to change the settings from the cli (maybe it's possible through websocket but I couldn't find a home assistant service to do it). I ended up editing settings.json and restarting.

### What Platform / OS are you running?

Linux

### What version are you running?

4.2.5

### Anything in the logs or a references that might be useful?

```txt
systembridgebackend==4.2.5
systembridgecli==4.0.5
systembridgeconnector==4.1.2
systembridgefrontend==4.0.3
systembridgemodels==4.1.0
systembridgeshared==4.0.4
```

**Comment by timmo001** [comment]
You should still have access to the settings via the frontend, which is linked to via the home assistant device page under "visit".

If you are using the python variant, make sure to install systembridgefrontend and restart the backend

**Comment by bwduncan** [comment]
oops i read this and wasn't immediately able to try it, but i did later so:

thanks so much, that explains perfectly. closing :smiley:
