### ISSUE TITLE
Home Assistant Integration: "Open Path" fails with error

### ISSUE THREAD

**Issue by sgoffman** [timmo001/system-bridge#3122]
### Description

Since HA v2024.7, calling System Bridge > Call Service > "Open Path" fails with the error "The service call requires responses and must be called with return_response=True".

### What Platform / OS are you running?

Linux

### What version are you running?

4.1.10

### Anything in the logs or a references that might be useful?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:283
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:17:14 PM (3 occurrences)
Last logged: 2:26:22 PM

[140643181694256] The service call requires responses and must be called with return_response=True
```

**Comment by timmo001** [comment]
This log comes from home assistant and after some testing of the integration, should not throw this message now
