### ISSUE TITLE
Keypress media keys not working, nor do media controls

### ISSUE THREAD

**Issue by JuliaSoriaSmith** [timmo001/system-bridge#3177]
### Description

The media controls for System Bridge are not working. Initially I thought it was a home assistant bug as per this issue [Systembrigde integration: Keypress media keys not working, nor do media controls](https://github.com/home-assistant/core/issues/123246) but after doing some debugging with the API I think its a system bridge issue.

The media controls for System Bridge are not working. When I call the following action:

action: system_bridge.send_keypress
data:
bridge: <device_id>
key: audio_mute

I get the following back:
id: ac56fc829705490eb890f116f141bda3
type: ERROR
data:
token:
id: ac56fc829705490eb890f116f141bda3
event: KEYBOARD_KEYPRESS
data:
key: audio_mute
subtype: TIMEOUT
message: Timeout waiting for response
module: null

I tried this instead of using the media controls since they do not work also.
Calling the following returns nothing, there is no output.

action: media_player.media_pause
data: {}
target:
device_id: <device_id>

There is nothing in the home assistant log for the above service call.

I have tried some debugging, I do not believe its on the home assistant end. I believe its on the system-bridge side not handling the media command properly.

I wrote this JS script to debug:

import asyncio
import websockets
import json

async def receive_data(token):
uri = "ws://127.0.0.1:9170/api/websocket"
message = {
"id": "abc123",
"token": token,
"event": "MEDIA_CONTROL",
"data": {
"action": "PAUSE"
}
}

async with websockets.connect(uri) as websocket:
    # Send JSON data
    await websocket.send(json.dumps(message))

    # Keep connection alive to receive all responses
    while True:
        response = await websocket.recv()
        print("Received:", response)

asyncio.get_event_loop().run_until_complete(receive_data(token))

This is what my log said:

2024-08-12 12:50:02 INFO (MainThread) [uvicorn.error] ('127.0.0.1', 57136) - "WebSocket /api/websocket" [accepted]
2024-08-12 12:50:02 INFO (MainThread) [uvicorn.error] connection open
2024-08-12 12:50:02 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: MEDIA_CONTROL
2024-08-12 12:50:04 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update took 0 seconds
2024-08-12 12:50:04 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Scheduled next update for: 2024-08-12 12:50:09.954594
2024-08-12 12:50:04 INFO (Thread-4 (_run)) [systembridgebackend.modules.media.Media] Updating media data

It did not pause the audio. Using other web socket commands to get module data back works so its not my script that isnt working.

When sending the pause command via home assistant, it also doesnt pause and the backend logs say:

2024-08-12 12:52:21 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: MEDIA_CONTROL

### What Platform / OS are you running?

Windows

### What version are you running?

Windows 11: 23H2

**Comment by timmo001** [comment]
Please update to [4.1.11](https://github.com/timmo001/system-bridge/releases/tag/4.1.11)+ and Home Assistant 2024.8.2+ and let me know if your issues is resolved

**Comment by JuliaSoriaSmith** [comment]
Hello,

I am now on version 4.1.13 of systembridge, and my HA version is 2024.8.2

**Comment by JuliaSoriaSmith** [comment]
I did some more debugging, and I think the issue is in actually calling the media functions on the backend. I managed the media code to get this test-script:

import asyncio
from winsdk.windows.media import (  # pylint: disable=import-error
    MediaPlaybackAutoRepeatMode,
    control as wmc,  # pylint: disable=import-error
)

async def pause_media():
    # Request the session manager and try to pause the media
    sessions = (
        await wmc.GlobalSystemMediaTransportControlsSessionManager.request_async()
    )

    session = sessions.get_current_session()
    
    await session.try_pause_async()

# Call the function asynchronously
async def main():
    await pause_media()

# Run the main function
asyncio.run(main())


This pauses the current media session, and is based off of whats in the media backend. 
I'm having issues compiling the main frontend so I cant really debug why its not calling it properly

**Comment by Buka666** [comment]
Hello,
Version 4.1.13 of systembridge, HA version is 2024.11.3, and the media keys still do not work.
