### ISSUE TITLE
Unable to find media module in HA (Windows headless / Linux)

### ISSUE THREAD

**Issue by DeFlanko** [timmo001/system-bridge#3184]
### Description

Still not working. Im OP... from this thread https://github.com/timmo001/system-bridge/issues/3152#issuecomment-2294423466

![image](https://github.com/user-attachments/assets/9cbb8718-e3e9-418f-9454-f115ccb3bc7d)

![image](https://github.com/user-attachments/assets/c0cc52bb-dc71-445c-abf0-6eee76b75ee3)

![image](https://github.com/user-attachments/assets/ccb6bb8b-f08e-47d9-9710-b5030801b3f1)

![image](https://github.com/user-attachments/assets/2face28f-fbd2-4b7b-ab41-65c86e9aeea4)

### What Platform / OS are you running?

Windows

### How is System Bridge Being Ran?

Standalone (executable)

### What version are you running?

4.1.11

### Additional information

![image](https://github.com/user-attachments/assets/440892db-2329-45f9-b51b-65f2b7917853)

**Comment by timmo001** [comment]
Just as an aside, I'm assuming you are running the app as a service, as this is a headless VM setup?

**Comment by timmo001** [comment]
https://github.com/timmo001/system-bridge-backend/blob/69d689ed0d705f25545849ffcfbd138bc68c89eb/systembridgebackend/server/websocket.py#L614-L626

**Comment by DeFlanko** [comment]
No the device im running Systembridge on is a physical PC, the instance that Homeassistant is running on is a VMware image. (same pc, different IP's -- they've always been able to see each other in the past too -- no issue with ingress and egress between the two IP's )

**Comment by DeFlanko** [comment]
Task Scheduler:
![image](https://github.com/user-attachments/assets/5e6f05c6-922b-42b1-a74f-73faf57489cb)

![image](https://github.com/user-attachments/assets/c524071e-60a2-4388-89e0-2d239dc79855)

![image](https://github.com/user-attachments/assets/e269b82c-0db8-438c-8d2b-856a97404fd4)

Its the only way i could get it to run on startup without me being there. (yeah kinda headless)

**Comment by timmo001** [comment]
Next version is going out, fixed on a linux server, not tested in your setup but I have added failsafes to make sure the media data is now populated empty

**Comment by DeFlanko** [comment]
That worked!

![image](https://github.com/user-attachments/assets/4725d391-2243-4e37-a020-ef784d212ded)

![image](https://github.com/user-attachments/assets/313a4b2e-6975-46a3-9952-f04286222f72)

![image](https://github.com/user-attachments/assets/ed7293b4-4c9a-4293-8ae3-99f8b02f5151)

![image](https://github.com/user-attachments/assets/45254d0e-862f-4302-bce2-6d5b9677190d)

**Comment by DeFlanko** [comment]
Thanks @timmo001
