### ISSUE TITLE
Can't add integration to HA

### ISSUE THREAD

**Issue by RafaelSoaresP** [timmo001/system-bridge#3226]
### Description

Attempting to add the System Bridge integration on Home Assistant running under CasaOS returns "failed to connect".

Client is running Windows 11, with ports opened on firewall, and data is accessible via link (http://10.0.0.200:9170/app/data.html?apiKey=[guid]&apiPort=9170&token=[TOKEN])

Every connection attempt I make, the logs on the HA container show as following:

> 
> homeassistant  | [31m2024-09-02 19:28:14.975 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> homeassistant  | Traceback (most recent call last):
> homeassistant  |   File "/usr/local/lib/python3.12/site-packages/systembridgeconnector/websocket_client.py", line 591, in listen
> homeassistant  |     await self.listen_for_messages(callback=_callback_message)
> homeassistant  |   File "/usr/local/lib/python3.12/site-packages/systembridgeconnector/websocket_client.py", line 607, in listen_for_messages
> homeassistant  |     await callback(message)
> homeassistant  |   File "/usr/local/lib/python3.12/site-packages/systembridgeconnector/websocket_client.py", line 579, in _callback_message
> homeassistant  |     else model(**message[EVENT_DATA]),
> homeassistant  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> homeassistant  | TypeError: System.__init__() got an unexpected keyword argument 'run_mode'[0m
> homeassistant  | [33m2024-09-02 19:28:29.930 WARNING (MainThread) [homeassistant.components.system_bridge.config_flow] Timed out connecting to 10.0.0.200: [0m

HA itself shows this on it's logs (sorry for any mistakes, but I had to translate some parts)

> Logger: homeassistant.components.system_bridge.config_flow
> Source: components/system_bridge/config_flow.py:96
> Integration: System Bridge (documentation, issues)
> Happened for the first time: 19:22:14 (6 occurrences)
> Last record: 19:28:29
> 
> Timed out connecting to 10.0.0.200:

systembridgebackend.log shows:

> 
> 2024-09-02 19:46:45 ERROR (MainThread) [asyncio] Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
> handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
> Traceback (most recent call last):
>   File "asyncio\events.py", line 88, in _run
>   File "asyncio\proactor_events.py", line 165, in _call_connection_lost
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 

### What Platform / OS are you running?

Windows

### How is System Bridge Being Ran?

Standalone (executable)

### What version are you running?

4.1.13

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by timmo001** [comment]
Are you on th latest version of Home Assistant?

**Comment by RafaelSoaresP** [comment]
Good call! I was actually on 2024.5.5 that's available as default on CasaOS. Upgrading the container to the latest tag fixed the issue and it paired perfectly. 
Thanks a lot!
