### ISSUE TITLE
CPU Temperature Wrong

### ISSUE THREAD

**Issue by joshgibbons1** [timmo001/system-bridge#3265]
### Description

Wrong CPU temperature is reported, for example it shows 54C whereas other apps such as HWiNFO and Corsair iCUE show 74C

### What Platform / OS are you running?

Windows

### How is System Bridge Being Ran?

Standalone (executable)

### What version are you running?

4.1.13

### Additional information

![image](https://github.com/user-attachments/assets/1cdbf2eb-0383-4654-8dc8-9fe449d26dbe)

**Comment by timmo001** [comment]
The temperature is based on one of the values from [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor). All these tools report different values, but the values look for `k10temp`,`coretemp`,`atk0110`. 

https://github.com/timmo001/system-bridge-backend/blob/master/systembridgebackend/modules/cpu.py#L126-L195

If you can find a similar value in LibreHardwareMonitor and believe the value used is incorrect in System Bridge, please change your log level to debug, restart the application and update the description with the logs for CPU temperature. These will look something like `Found CPU temperature: ...`

**Comment by joshgibbons1** [comment]
Thanks for the quick reply. It appears to be getting the data from 'CCDs Average (Tdie)' instead of 'Core (Tctl/Tdie)' which is what all the other applications seem to be using.

![image](https://github.com/user-attachments/assets/f35c2bb1-ec04-42ba-88a3-b66ded784ddc)
