### ISSUE TITLE
Ability to request system idle time

### ISSUE THREAD

**Issue by lordmundi** [timmo001/system-bridge#352]
# Description

It would be good if one of the items available through the API is the system OS idle time. This could then be used as presence detection.

## Suggested Actions
Make one item in the API (perhaps in the OS section) the idle time in seconds.

**Comment by lordmundi** [comment]
one note of caution for windows idle time... some of the built-in functions have data types which will roll to zero after a long uptime on the system.  In Python I was able to get around this with:

```
def get_idle_duration():
    ticks = win32api.GetTickCount()
    # After fourty something days, GetTickCount will roll to a negative number
    if (ticks < 0):
        ticks += 2**32
    secs_idle = (ticks - win32api.GetLastInputInfo()) / 1000.0
    print(ticks, " - ", win32api.GetLastInputInfo(), " = ", secs_idle)
    return secs_idle
```

**Comment by timmo001** [comment]
Do you know of a cross-platform library for nodejs?

I don't want to diverge too far between platforms. For example, if there is a solution that can get system data that works with all platforms, that would be preferred. Of course, there are some specific platform information that may be useful. The current solution for data is [system information](https://systeminformation.io) but there may be additional libraries or additions that could be added to that library

**Comment by lordmundi** [comment]
a few options:

https://github.com/bithavoc/node-desktop-idle (which I think is the same as
https://www.npmjs.com/package/desktop-idle)
https://github.com/anaisbetts/node-system-idle-time
https://www.electronjs.org/docs/api/power-monitor

not sure which one is best for this project.

**Comment by lordmundi** [comment]
fantastic!
