### ISSUE TITLE
Windows Launch on Startup Not Working

### ISSUE THREAD

**Issue by SilentException** [timmo001/system-bridge#374]
Windows 10
System Bridge v1.6.0 (planning to try v1.7.0 but don't think it will be any different)

When turning on auto launch in settings, the registry key is generated but the app isn't started at boot. I believe it is because of the UAC elevation system-bridge.exe needs for before executing. 

This can be worked around by using Windows Task Scheduler to run the executable or using Windows service. I tried the latter by wrapping execution using WinSW but had no luck yet. The system-bridge.exe starts but terminates 5 seconds later. Might be because the service runs using Local System account but I have no logs other than this entry in Event Log: "Child process 'system-bridge (10996)' finished with code 0.". Task Scheduler method works OK. Attached is the auto run task exported to XML from Task Scheduler if it helps. Thanks for looking.

[Autorun for SilentException.zip](https://github.com/timmo001/system-bridge/files/6604043/Autorun.for.SilentException.zip)

**Comment by WhiteNight121** [comment]
having the same issue in 1.7.2

**Comment by Salvora** [comment]
same here

**Comment by joelvalentijn** [comment]
same here
