### ISSUE TITLE
Non-Unique ID's for "Spaced Used" Entities

### ISSUE THREAD

**Issue by keithcorradi** [timmo001/system-bridge#449]
### Description

If you have multiple devices configured, for Windows, they will all use the "C:" natively. However, the "unique id" for both devices is simply: "unique_id": "C:". This causes two issues. One of which is annoying, and another which actually causes issues:
1. Annoying: errors are displayed that there is a unique ID overlap. Not a huge deal
2. Real issue: since the ID's are not unique, they appear to get transposed from one device to another. For example, if you have "Space_USED_X1" entity for device X1...if you add another device called X2, the "Space_USED_X1" entity will now appear in X2, and X2 will not have a "Space_Used_X2" entity. This issue also occurs for all other drives listed (Z:, Y:, D:, etc.)

To be clear; this very well be my setup. However, I have tried it on three different windows machines and they all react the same. I've tried deleting all the integrations, starting from scratch, manually updating the unique_id, and nothing works.

I'm running this on a Rasp 4; no config errors appear at any point. 

### What Platform / OS are you running?

Linux

**Comment by timmo001** [comment]
I assume this is for the Home Assistant Integration?

Please open this issue at [Home Assistant Core](https://github.com/home-assistant/core/issues/new). Thanks

**Comment by keithcorradi** [comment]
Thanks Aidan. This is for the integration, the system-bridge integration;
and it's the *only* one I have this issue with at present. With a single
*bridge* everything works fine, it's brilliant in fact, but if I add a
second computer, the "c: space used" gets moved to the other computer's
device entities and the new one doesn't have an equivalent. To be clear,
this is not a show-stopper, but i have to imagine this is not a unique
experience.

Thanks!
