### ISSUE TITLE
Cannot get audio from loudness module

### ISSUE THREAD

**Issue by atebeta** [timmo001/system-bridge#498]
### Description

I'm unable to get the current volume or control it with the audio endpoint. Seems to be an issue with the "adjust_get_current_system_volume_vista_plus.exe" as per logs below.

### What Platform / OS are you running?

Windows

### Anything in the logs or a references that might be useful?

```txt
Cannot get audio from loudness module: Command failed with ENOENT: C:\Users\<hidden>\AppData\Local\system-bridge\app-1.7.2\resources\app.asar\node_modules\loudness\impl\windows\adjust_get_current_system_volume_vista_plus.exe
spawn C:\Users\<hidden>\AppData\Local\system-bridge\app-1.7.2\resources\app.asar\node_modules\loudness\impl\windows\adjust_get_current_system_volume_vista_plus.exe ENOENT
```

**Comment by timmo001** [comment]
Fixed in recent commits. This package has been replaced
