### ISSUE TITLE
'Missing device' when using 'system_bridge.send_command' in Home Assistant

### ISSUE THREAD

**Issue by atebeta** [timmo001/system-bridge#500]
### Description

Trying to send a command via Home Assistant, but logs keep saying 'Missing device'. 

service: system_bridge.send_command
data:
  bridge: PC
  command: echo
  arguments: hello

Tried using all sorts of different names for the bridge, PC is what system bridge identifies as Host -

### What Platform / OS are you running?

Windows

### Anything in the logs or a references that might be useful?

```txt
2021-07-09 13:46:03 WARNING (MainThread) [homeassistant.components.system_bridge] Missing device: PC
```

**Comment by timmo001** [comment]
This looks like a misconfiguration in Home Assistant. If the problem persists, please open it at the Home Assistant Core repository. Issues here are for the main application, not the integration

**Comment by atebeta** [comment]
OK thanks will do. Can you confirm that the value for device is supposed to be the host name?
