### ISSUE TITLE
Can't read "C: Space Used" from two Windows PCs

### ISSUE THREAD

**Issue by masterfish1** [timmo001/system-bridge#546]
### Description

I have two Windows PCs (named MYPC and Windows-PC). If I add the integration for MYPC first and then Windows-PC, Windows PC shows the "C: Space Used" of MYPC.

If I set up the integration of Windows-PC first and then MYPC, MYPC show the "C: Space Used" of Windows-PC.

All other variables work fine. 

### What Platform / OS are you running?

Windows

**Comment by timmo001** [comment]
This is a [Home Assistant Core](https://github.com/home-assistant/core) issue, however, the unique names are different. I have also seen this where the C: drive seems to jump across to the other device, even though it is configured to use the name of the device in its Unique ID / Entity ID

**Comment by timmo001** [comment]
Found fix in https://github.com/home-assistant/core/pull/53446. The unique id was being set to the drive letter instead of a unique key by mistake

**Comment by timmo001** [comment]
Merged, will appear in the next version of Home Assistant
