### ISSUE TITLE
New user documentation

### ISSUE THREAD

**Issue by LukeMondy** [timmo001/system-bridge#548]
### Description

Hey, this looks like a great piece of software. I've installed it on my Debian system, and found the binaries, but I am at a bit of a loss how to actually use and interact with it.

I can run it, and it prints out a bunch of debug info, but no GUI or toolbar icon appear. Providing `--help` on the commandline didn't seem to make a difference, and I can't seem to find any info on the website on what to expect either.

Would you be able to provide some docs on how to use the tool, what to expect on startup, and where things like config files go?

Thanks

**Comment by timmo001** [comment]
Please take a look at https://github.com/timmo001/system-bridge-site and https://system-bridge.timmo.dev

If you have any suggestions for docs to add, please raise them here:

https://github.com/timmo001/system-bridge-site/issues
