### ISSUE TITLE
Kaspersky reports system bridge as trojan.

### ISSUE THREAD

**Issue by Salvora** [timmo001/system-bridge#552]
### Description

I just upgraded from 1.7.2 to 2.1.0 but my Kaspersky went crazy after the installation.

Event: Malicious object detected
Application: Node.js JavaScript Runtime
User: GT95\pc
User type: Active user
Component: System Watcher
Result description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object path: p:\program files\system bridge
Object name: system-bridge.exe
Reason: Databases
Databases release date: Today, 18/07/2021 02:23:00

### What Platform / OS are you running?

Windows

### What version are you running?

2.1.0

**Comment by timmo001** [comment]
`Reason: Databases`

What does that even mean? The app uses an SQLite DB stored in `%appdata%\system-bridge\system-bridge_v1.db`. GitHub scans the codebase for any issues. There are no libraries with security holes currently being reported.

IMHO, the trojan is kaspersky. This is a false positive. I'd suggest whitelisting the exe and if you are super security conscious building the app yourself

**Comment by Salvora** [comment]
I am not sure why exactly it reports this as trojan. There is no detailed report.
Detailed info regarding false positives here:
https://support.kaspersky.com/viruses/answers/1870
