### ISSUE TITLE
Command prompt windows pop up when using /audio end point

### ISSUE THREAD

**Issue by atebeta** [timmo001/system-bridge#558]
### Description

A command prompt window pops up and quickly closes when using the /volume endpoint. Tested with both /audio and setting the volume with /audio/volume.

Also in the documentation, the end points for volume up and volume down are both /audio/volume/ - assume this is a mistake.

### What Platform / OS are you running?

Windows

### What version are you running?

2.0.1

**Comment by timmo001** [comment]
Thanks for the tip, the docs should now be showing the correct endpoint for audio/volumeup etc. now.

The command prompt windows are from other libraries which are out of my control. There is likely a reason such not as being able to run certain commands without a window

**Comment by atebeta** [comment]
So there is nothing you can do about the command prompt window? I was hoping to use the volume end point as a sensor,but not really usable if the command prompt window pops up every time the sensor is updated.

**Comment by timmo001** [comment]
This appears to happen for multiple functions of the app. I have recently added MQTT functionality (in development) and it appears to be popping up a window for every event which isn't great as it is taking focus from the window

**Comment by timmo001** [comment]
I will open a separate issue for this
