### ISSUE TITLE
2.4.2 Integration won't configure in Home Assistant and going to the ipaddress:9170 and 9172 gives error messages.

### ISSUE THREAD

**Issue by julianrinaldi** [timmo001/system-bridge#689]
### Description

The integration fails to install. I have System Bridge on a Windows 10 computer. Going to ipaddress:9170 gives this error:

{"statusCode":404,"message":"Cannot GET /","error":"Not Found"}

Going to 9172 gives this error:

Upgrade Required

I'm on 2.4.2, so I'm not sure why an upgrade would be required.

It publishes everything to my MQTT broker without issue.

### What Platform / OS are you running?

Windows

### What version are you running?

2.4.2

**Comment by timmo001** [comment]
Port 9172 is the default websocket port. 9170 is the default API port.

This is also an issue for https://github.com/home-assistant/core not here, as this is the application.
