### ISSUE TITLE
Windows Sensors Lib - Incorrect Path

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#827]
### Description

Windows Sensors Library fails to load. Introduced in #825 

### What Platform / OS are you running?

Windows

### What version are you running?

v2.6.0 Development - Built

### Anything in the logs or a references that might be useful?

```txt
2021-09-19 22:59:37 error: GraphicsService - Error: Command failed with exit code 1: C:\snapshot\system-bridge\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
```

**Comment by oliverroozen** [comment]
I have this while running Windows 11 insider preview build 22458, on 2.5.0. It was happening on earlier builds of W11 though.
