### ISSUE TITLE
Memory information backwards in Linux Mint

### ISSUE THREAD

**Issue by julianrinaldi** [timmo001/system-bridge#840]
### Description

I just installed System-Bridge on a computer running Linux Mint.

My approximate memory usage is 1.7GB of 12G. However, System-Bridge has the logic backwards and thinks I'm using +98% of my memory.

### What Platform / OS are you running?

Linux

### What version are you running?

2.5

**Comment by timmo001** [comment]
You'll want to report this to https://github.com/sebhildebrandt/systeminformation as this is where the information comes from

**Comment by sebhildebrandt** [comment]
@julianrinaldi ... investigating this on our side (systeminformation) ...

**Comment by julianrinaldi** [comment]
> You'll want to report this to https://github.com/sebhildebrandt/systeminformation as this is where the information comes from

Is it possible you're using the MemFree number instead of MemAvailable?

In this screenshot the MemAvailable is the number that's reporting the correct memory usage, which is what the System Monitor is reporting.
![CleanShot 2021-09-22 at 16 24 06](https://user-images.githubusercontent.com/492435/134421135-40098574-285f-44e0-a255-13c3fbe48157.png)

**Comment by sebhildebrandt** [comment]
@timmo001 so after investigation, we see that there is no problem in the systeminformation package. The issue (that was open there) is already closed.
