### ISSUE TITLE
Cant uninstall

### ISSUE THREAD

**Issue by heiblum** [timmo001/system-bridge#989]
### Description

Hi,

Cant uninstall the program.

I uninstalled it with the uninstaller but it keep version 0.0 and keep startup with my pc.

### What Platform / OS are you running?

Windows

### What version are you running?

Latest Oct-17-21

**Comment by timmo001** [comment]
You can uninstall the application by running the `uninstall.exe` which is found in the start menu or by default in `C:\Users\USER\AppData\Local\System Bridge`. If you are missing this script, you can manually remove this directory.
